### ISSUE TITLE
Scripts are not executed, and the information is not displayed in the log.

### ISSUE THREAD

**Issue by reu-res** [0vercl0k/ollydbg2-python#6] opened 2014-01-29 11:04 UTC
![1](https://f.cloud.github.com/assets/1050186/2028721/0a9ba0f8-88d5-11e3-985c-745bbc528824.png)

**Comment by 0vercl0k** [comment] 2014-01-29 18:07
Can I have more details? Have you compiled yourself the python-loader? Which version of Python have you installed?

Can you just try to run a dummy Python file that writes a file on the disk (to be sure the Python is actually being evaluated)?

My guess is that the stream hooker (https://github.com/0vercl0k/ollydbg2-python/blob/master/ollyapi/__init__.py#L11) hasn't been executed.

On my development set-up I get:

![testing](https://f.cloud.github.com/assets/1476421/2032544/e480ffda-8910-11e3-82d6-97ba2f6ef4e7.png)

**Comment by reu-res** [comment] 2014-01-29 18:36
All compiled itself. Python 2.7.5.

``` python
import ollyapi  # without importing ollyapi file 'test.txt' creates

with open('test.txt', 'w') as f:
    f.write('Hello world')
```

**Comment by 0vercl0k** [comment] 2014-01-29 18:45
And with the import ollyapi it doesn't work?

**Comment by reu-res** [comment] 2014-01-29 18:48
Yes

**Comment by 0vercl0k** [comment] 2014-01-29 18:52
All right, that's why you don't see the messages on the log window then :)
Can you explain the organization of the directories you have?
OllyDbg should be in the directory than ollyapi, samples a bit like this:

```
D:\Codes\OllyDBG2-Python>dir

 Directory of D:\Codes\OllyDBG2-Python

01/12/2013  21:28    <DIR>          .
01/12/2013  21:28    <DIR>          ..
21/03/2008  00:44         1 061 944 dbghelp.dll
25/09/2013  11:53    <DIR>          ollyapi
17/07/2012  19:46           380 815 OllyDbg 2.0 Brief Help.pdf
18/11/2012  20:46         2 547 200 ollydbg.exe
29/01/2014  18:10            14 197 ollydbg.ini
24/09/2013  15:47    <DIR>          plugins
24/09/2013  13:17    <DIR>          samples
```

**Comment by reu-res** [comment] 2014-01-29 18:58
OllyDbg directory

```
D:\tools\OD2>dir

29.01.2014  20:54    <DIR>          .
29.01.2014  20:54    <DIR>          ..
21.03.2008  01:44         1 061 944 dbghelp.dll
27.09.2013  01:01         5 696 469 help.pdf
25.11.2012  22:30             8 192 loaddll.exe
29.01.2014  14:59    <DIR>          ollyapi
27.09.2013  01:01         2 650 624 ollydbg.exe
29.01.2014  20:24            15 363 ollydbg.ini
29.01.2014  12:12    <DIR>          plugins
29.01.2014  12:13    <DIR>          samples
29.01.2014  13:36    <DIR>          udd
```

ollyapi directory

```
D:\tools\OD2>dir ollyapi

29.01.2014  14:59    <DIR>          .
29.01.2014  14:59    <DIR>          ..
29.01.2014  11:55             8 459 breakpoints.py
29.01.2014  14:59             8 451 breakpoints.pyc
29.01.2014  11:55             4 315 memory.py
29.01.2014  12:11           416 203 python_bindings_swig.py
29.01.2014  14:59           309 289 python_bindings_swig.pyc
29.01.2014  11:55            12 942 sym.py
29.01.2014  11:55             7 930 threads.py
29.01.2014  11:55            14 773 utils.py
29.01.2014  12:11           972 288 _python_bindings_swig.pyd
29.01.2014  11:55             5 059 __init__.py
29.01.2014  14:59             4 882 __init__.pyc
```

**Comment by 0vercl0k** [comment] 2014-01-29 19:09
Hum ok, that's fine.
Can you try to edit the **init** file and add some code before/after the imports to write some message in a log file on the disk? Just to see which line is failing

**Comment by reu-res** [comment] 2014-01-29 19:35
Problem in python_bindings_swig.py
`ImportError: DLL load failed: The specified procedure could not be found.`

**Comment by 0vercl0k** [comment] 2014-01-29 19:43
OK so it basically means your SWIG bindings don't work, never had this issue. Is the .pyd file an x86 dll? Can you load it in LPE to check that please?

**Comment by reu-res** [comment] 2014-01-29 20:10
Yes, this is x86 dll. I don't know what is LPE.

**Comment by reu-res** [comment] 2014-01-29 20:11
Can you give me your `_python_bindings_swig.pyd` ?

**Comment by 0vercl0k** [comment] 2014-01-29 20:15
LPE=LordPE. Sure I can upload you somewhere my files let me do that

**Comment by 0vercl0k** [comment] 2014-01-29 20:29
There you go:
http://www.filedropper.com/pythonbindingsswig

**Comment by reu-res** [comment] 2014-01-29 20:36
The same error.

**Comment by 0vercl0k** [comment] 2014-01-29 20:40
Are you sure the problem is in python_bindings_swig.py then ? In your dir command I can see a .pyc that indicates it has been loaded at least once

**Comment by 0vercl0k** [comment] 2014-01-29 20:45
Otherwise, try to remove your ollyapi directory and replace it with that one http://www.filedropper.com/ollyapi

**Comment by reu-res** [comment] 2014-01-29 20:50
Yes. First load `__init__.py` compile and execute, in him at first load `from breakpoints import *` again compile and execute, in him load `from python_bindings_swig import *` again compile and execute and in `python_bindings_swig.py` exception occurs and after this don't load anything.

**Comment by reu-res** [comment] 2014-01-29 20:55
The same error.

**Comment by reu-res** [comment] 2014-01-29 20:57
Maybe problem in ollydbg. In my in VERSION_INFO write 2.1.0.4 version.

**Comment by 0vercl0k** [comment] 2014-01-29 21:00
oh, it seems that I have the same behavior with the last version of OllyDbg, let me investigate that

**Comment by reu-res** [comment] 2014-01-29 21:11
yes, tried on previous version and work fine, would like to support the latest version OllyDbg.

**Comment by 0vercl0k** [comment] 2014-01-29 21:14
I think I've understood, my guess is OllyDbg (the new version) doesn't export the same functions ; that would explain why it doesn't load

**Comment by 0vercl0k** [comment] 2014-01-30 22:01
It was the API Fillcombowithcodepages (https://github.com/0vercl0k/ollydbg2-python/commit/4f5206bdff81df9023200a3673df42c354f05c3e) that isn't anymore exported by OllyDbg, I tested on the last version it should work for you.
Waiting for you to confirm that & closing the issue :)

**Comment by reu-res** [comment] 2014-01-30 22:30
Yes, all works fine :)

**Comment by 0vercl0k** [comment] 2014-01-30 22:33
Great :). Looking forward to seeing what do you think about it ; feel free to shoot me an email

**Closed as completed by 0vercl0k** 2014-01-30 22:33 UTC
